### ISSUE TITLE
Set default table in table group

### ISSUE THREAD

**Issue by KyleStorck** [microsoft/microsoft-performance-toolkit-sdk#127]
I'm talking about the group of tables in Graph Explorer that are grouped by TableDescriptor.Category. It looks like the default table that is displayed while collapsed is the first alphabetically. Is there a way to set that default table besides alphabetically?

![image](https://user-images.githubusercontent.com/1233941/132411497-2a653ace-0ca5-4983-ab6f-6e74e06e6bed.png)

![image](https://user-images.githubusercontent.com/1233941/132411517-8180a936-2cba-42b4-8414-3869e21dfe87.png)

**Comment by mslukebo** [comment]
Hi,

There is unfortunately no way to do this with plugins at the moment.

-Luke

**Comment by KyleStorck** [comment]
Got it. Thanks for the response.
