### ISSUE TITLE
Using the SDK Documentation has missing images.

### ISSUE THREAD

**Issue by zachnew-msft** [microsoft/microsoft-performance-toolkit-sdk#19]
The image links in the 'documentation/Using-the-SDK/Creating-your-project.md' document are broken. The images are not being displayed.

Repro:
Navigate to documentation/Using-the-SDK/Creating-your-project.md

Expected:
The images are displayed in the document.

Actual:
The links are displayed and 404 when followed.

The links in question are:
https://github.com/microsoft/microsoft-performance-toolkit-sdk/raw/develop/.attachments/VS2017_Create_New_Project-f151d280-ecd7-45be-bde0-6ac5f23340e8.PNG

https://github.com/microsoft/microsoft-performance-toolkit-sdk/blob/develop/.attachments/VS2017_New_DotNetStandard_20_Project-33e8f885-59cc-436b-bb41-ec56b872d42d.PNG

**Comment by mslukebo** [comment]
Fixed with #29
