### ISSUE TITLE
Changing the allTablesMapping parameter of the CustomDataProcessorBase constructor does not change the tables that appear in WPA

### ISSUE THREAD

**Issue by mslukebo** [microsoft/microsoft-performance-toolkit-sdk#32]
It would make sense for a plugin to change which tables are passed into a simple custom data processor's `BuildTableCore` method. The only way the SDK currently exposes a way to manipulate which tables do this is with the `allTablesMapping` argument to the `CustomDataProcessorBase` constructor. However, changing this parameter has no effect on tables showing up in WPA.

This is because the SDK is not implementing any logic for what tables get hooked up to which processors. Perhaps this parameter (and the `metadataTables` parameter) should be removed from this constructor entirely.

**Comment by trgibeau** [comment]
Follow up

**Comment by mslukebo** [comment]
This will be solved by #33
