### ISSUE TITLE
How can I get the DataCookerPath and DataOutput (Name/Type) of other close-source plugins?

### ISSUE THREAD

**Issue by 0xhellord** [microsoft/microsoft-performance-toolkit-sdk#388]
According to [https://github.com/microsoft/microsoft-performance-toolkit-sdk/blob/main/documentation/Architecture/The-Data-Processing-Pipeline.md](url):
 

> Allow external binaries, such as other plugins, access to the output of these transformations (as in extend the plugin defining the transformation)

> To query a DataOutput, the querying code only needs to know:
    > The DataCookerPath for the DataCooker it wishes to receive data from
    > The (string) name of the DataOutput property of that DataCooker
    > The type of the DataOutput property
    > Because the querying code only needs these three properties, external assemblies - even those without access to any DataCookers' source code - can query the SDK for data from any DataCooker which is loaded.

 

But how can we find out the `DataCookerPath` and `DataOutput(naeme & type)` of other close-source plugins?

**Comment by mslukebo** [comment]
Hi @0xhellord ,

The authors of the closed source plugin would need to somehow publish this information for you to consume. If the properties are simple types (strings, ints, etc), the plugin authors could publish a list of data cooker paths and properties; you wouldn't need to compile directly against the plugin.

If, however, the properties output custom types, you will need to compile against the plugin. The plugin authors could publish a NuGet package with their plugin's types.
