### ISSUE TITLE
Support for ETW event processing?

### ISSUE THREAD

**Issue by tpn** [microsoft/microsoft-performance-toolkit-sdk#43]
I have a general question regarding this WPA SDK project that I can't find answered elsewhere.  Based on the samples so far, it seems the emphasis is on being able to ingest non-.etl files and transform them in a way such that they can be visualized via WPA Tables.

The primary use case I'm interested in though is this: we have an ETL trace consisting of "NT Kernel Logger" data (call stacks, dispatch, context switch, all that sort of stuff), plus our own internal events (which typically get combined into a single final trace file via `xperf -stop "NT Kernel Logger" -stop "OurProduct Logger" -d combined.etl`).

WPA is great for allowing us to visualize the native kernel logging events it knows about, but it can't show us much about our custom events (other than that really generic view that I've forgotten the name of).

Now, WPA is already processing all the ETW events in the `combined.etl` trace file, so I guess I was wondering if there was a way (or plans for such a way) to hook into that existing ETW/ETL pipeline and get callbacks for events (perhaps by specifying the GUIDs we're interested in up-front).  I can't see anything like that currently, but I wanted to double check.

In lieu of an integrated pipeline... what would be the current option?  Custom data source that ingests .etl files, and use a C# .etl processing library (like TraceProcessor or whatever it's called) to extract events and make them play nice with the WPA plugin environment?  (Would this prevent WPA from displaying all the existing graphs/tables for events it knows about in the combined.etl trace?)

Hopefully the question makes sense, let me know if you need any more information (or if there's a better forum to ask questions, as this isn't really an issue per-se).

Thanks in advance!

**Comment by nibanks** [comment]
FYI, for [MsQuic](https://github.com/microsoft/msquic), we've worked with the WPA folks to put together a custom, open source plugin ([code](https://github.com/microsoft/msquic/tree/main/src/plugins/wpa)) for our custom ETW events ([manifest](https://github.com/microsoft/msquic/blob/main/src/manifest/MsQuicEtw.man)). Now, I'm not sure if that's exactly what you want here or not. It sounds like there might already be a plugin for some of your events, and that might just need to be updated. I'll let the WPA folks comment to that.

**Comment by tpn** [comment]
Actually, here's a concrete example of exactly the type of xperf invocation I'm talking about, using an open source project of mine (PerfectHash) as a reference.  The PerfectHash project emits .man-based ETW events based on various keywords (https://github.com/tpn/perfecthash/blob/main/src/PerfectHash/PerfectHashEvents.man).

A typical trace session, as adminstrator:

```
xperf -start "NT Kernel Logger" -on LATENCY+DISPATCHER+CPU_CONFIG+CSWITCH+DISK_IO+DPC+HARD_FAULTS+INTERRUPT+LOADER+MEMINFO+MEMINFO_WS+PERF_COUNTER+POWER+PROC_THREAD+PROFILE+PRIORITY+WDF_DPC+WDF_INTERRUPT -stackWalk Profile+CSwitch+ReadyThread+ThreadCreate+ThreadDelete+ProcessCreate+DiskFlushInit+DiskReadInit+DiskWriteInit -f kernel.etl -BufferSize 4096 -MinBuffers 4096 -MaxBuffers 8192 -MaxFile 8192 -FileMode Circular

xperf -start "PerfectHash Logger" -on PerfectHash:0x3e
```

I run my `PerfectHashCreate.exe` program, then issue:

```
xperf -stop "NT Kernel Logger" -stop "PerfectHash Logger" -d combined.etl
```

I then want to take that `combined.etl`, which contains all the kernel event goodies, plus events specific to my PerfectHash library, and load it into a single WPA instance, leveraging this SDK to visualize my PerfectHash events as first-class WPA tables (so they play nicely with things like zooming, filtering, etc).

Based on my review of the SDK so far, it seems like I'd need to achieve this by writing a custom .etl processor -- if so, would that still allow the ability to depict the kernel events and my custom events in the same WPA session?

**Comment by tpn** [comment]
> FYI, for [MsQuic](https://github.com/microsoft/msquic), we've worked with the WPA folks to put together a custom, open source plugin ([code](https://github.com/microsoft/msquic/tree/main/src/plugins/wpa)) for our custom ETW events ([manifest](https://github.com/microsoft/msquic/blob/main/src/manifest/MsQuicEtw.man)). Now, I'm not sure if that's exactly what you want here or not. It sounds like there might already be a plugin for some of your events, and that might just need to be updated. I'll let the WPA folks comment to that.

Ah!  Very interesting!  So, it looks like:

a) Yes, you'd have to write your own .etl data processor for now (but that's pretty easy thanks to `Microsoft.Diagnostic.Tracing`).
b) Yes, you'd end up with a WPA session that displayed all the normal stuff like call stacks etc, in addition to your new tables/views provided by your plugin.

**Comment by nibanks** [comment]
Yes, our plugin only adds to existing WPA functionality. It doesn't overwrite or remove anything.

**Comment by tpn** [comment]
Great, thanks!  This answers all my questions, so I'll close out the issue.

**Comment by tpn** [comment]
I successfully got my plugin to depict my .etl-backed tables side-by-side with all the normal xperf-provided tables, which is awesome!  However, it doesn't work via the command line approach, i.e. when I did the following:

```
wpa -addsearchdir c:\foo -i c:\foo\trace.etl
```

It comes back with the following error:
```
No -processor was specified, and multiple plugins can handle the file `c:\foo\trace.etl'. Please specify the `processor' option to disambiguate.
```

If I added my plugin's `bin\Release` directory as a junction in `WPA\CustomDataSources`, then launch WPA with no arguments, then do File->Open and select the .etl file... it successfully loads both xperf-derived tables and those from my plugin.  So, it'd be nice if there was a way to replicate this behavior on the command line.

**Comment by mslukebo** [comment]
Hi @tpn,

When opening a file in WPA through File->Open, WPA will pass the file to _all_ data processors available to process it (unless overridden in the Window->Select Tables setting). When loading through the command line this does not happen, and the user must specify which processor (singular) to use.

A future WPA release will fix this issue, and allow opening your file through the command line.

In the future, if you have issues specific to WPA and not the SDK, please submit them through Feedback Hub.

**Comment by tpn** [comment]
That makes sense, thanks for the clarification; much appreciated!

**Comment by ivberg** [comment]
Just to add some easy links here, if you want to process ETW/.etl files programmatically it's recommended to use DataLayer / TraceProcessing. Here are the links:
https://www.nuget.org/packages/Microsoft.Windows.EventTracing.Processing.All
https://aka.ms/TraceProcessing
