### ISSUE TITLE
Is there support for callstack-style tables (i.e. for visualizing hierarchical relationships)?

### ISSUE THREAD

**Issue by tpn** [microsoft/microsoft-performance-toolkit-sdk#44]
WPA's call stack views are incredibly useful -- is it possible to replicate this behavior using the SDK?  I can't see any examples of it based on initial searches.

Context: the [EventSource Activities Specification](https://github.com/tpn/pdfs/blob/master/EventSource%20Activities%20Specification%20(2016).pdf) details a way of encoding hierarchical event details using the standard `Activity` and `RelatedActivity` GUIDs present in ETW events.  On page 4 of that document, they show an example of _PerfView_ depicting such events in a tree view:

![image](https://user-images.githubusercontent.com/629986/109351055-74995780-782d-11eb-8da0-11b23744a626.png)

The call stack view in WPA would be the equivalent of that tree view in PerfView.  Is there currently a way to do that programmatically via the SDK?  i.e. being able to build arbitrarily-deep trees that you can expand/collapse etc.  Just looking for pointers on what APIs I should be looking at if it is possible (or some existing WPA SDK plugins that leverage such functionality).

**Comment by trgibeau** [comment]
Hi @tpn, 

It is possible to create a hierarchical column (similar to the stack columns) in the SDK via the [AddHierarchicalColumn<T>](https://github.com/microsoft/microsoft-performance-toolkit-sdk/blob/develop/src/Microsoft.Performance.SDK/Processing/TableBuilderExtensions.cs#L84). 

We are working on a some samples to demonstrate, but the [Linux PERF plugin's CPU Sampling Table](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/blob/develop/PerfDataExtensions/Tables/CpuSamplingTable.cs#L183).

The AddHierarchicalColumn<T> requires a [ICollectionInfoProvider<T>](https://github.com/microsoft/microsoft-performance-toolkit-sdk/blob/develop/src/Microsoft.Performance.SDK/Processing/ICollectionInfoProvider%601.cs#L12).
Here is an example:
[ArrayAccessProvider<T>](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/blob/develop/PerfDataExtensions/Tables/AccessProviders/ArrayAccessProvider%601.cs#L9)

Hope this helps get you started!

**Comment by tpn** [comment]
Fantastic, thanks!
