### ISSUE TITLE
 -addsearchdir PATH does not work as expected

### ISSUE THREAD

**Issue by Alois-xx** [microsoft/microsoft-performance-toolkit-sdk#45]
I have compiled the sample and call then wpa (10.5.16.2) with 

` wpa -addsearchdir D:\Source\git\microsoft-performance-toolkit-sdk\samples\SimpleDataSource\bin\Debug\netstandard2.1`
which gives me as output
`At least one input file must be specified.`

This did not work.
But copying the dlls to C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\CustomDataSources\Simple did the trick. Am I missing something here?

**Comment by trgibeau** [comment]
Hi @Alois-xx,

The currently released preview version of WPA requires a input file to be passed in via the command line when using -addsearchdir. 

We will be removing the requirement in a future version, we will keep the issue open until that version is pushed publicly. 

The workaround of copying the data source into the CustomDataSource path is supported as well. 

Thanks,

Tristan

**Comment by Alois-xx** [comment]
I have also tried to use -i xx.txt but that leads to other errors. When I use as directory not the output but one folder above the plugin seems to be loaded, but I now get a different error

```
wpa -addsearchdir D:\Source\git\microsoft-performance-toolkit-sdk\samples\SimpleDataSource\bin -i D:\Source\git\microsoft-performance-toolkit-sdk\samples\SimpleDataSource\SampleTestFile.txt
```
This leads to 

![grafik](https://user-images.githubusercontent.com/408821/109456325-e0133d00-7a58-11eb-803f-d9cd96ee566b.png)

Not sure if that comes from previous saved table settings? I have deleted all my presets but the error still persists. 
My first error was that I did specify as serach directory the bin folder of my plugin. Plugins seem to be searched only in subfolders of the given folder but not if any plugins are in the folder located. 

```
wpa (19272): 5 exceptions
	The key already existed in the dictionary.:   The key already existed in the dictionary.: 1 exception
		System.Collections.Concurrent.ConcurrentDictionary`2[Microsoft.Performance.Shell.TableSelection.TableInfo,System.__Canon].System.Collections.Generic.IDictionary<TKey,TValue>.Add(!0,!1)
			System.Collections.Concurrent.ConcurrentDictionary`2[Microsoft.Performance.Shell.TableSelection.TableInfo,System.__Canon].System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(value class System.Collections.Generic.KeyValuePair`2<!0,!1>)
			Microsoft.Performance.CollectionExtensions.AddRange(class System.Collections.Generic.ICollection`1<!!0>,class System.Collections.Generic.IEnumerable`1<!!0>)
			Microsoft.Performance.Shell.TableSelection.TableSelectionService.GetDataTableDescriptions()
			Microsoft.Performance.Shell.TableSelection.TableSelectionService.LoadTableDescriptionsAndSelection()
			Microsoft.Performance.Threading.BackgroundWorkManager+<>c__DisplayClass5_0.<Post>b__0(class System.Object)
			
```

**Comment by trgibeau** [comment]
Hi @Alois-xx,

Is the Sample folder still copied into the CustomDataSource directory?

If so, WPA might be throwing an exception because the two data sources are conflicting with each other. 

Thanks,

Tristan

**Comment by mslukebo** [comment]
Hi @Alois-xx,

Can you check the contents of `D:\Source\git\microsoft-performance-toolkit-sdk\samples\SimpleDataSource\bin`? If there are two builds stored (e.g. a `Debug` build and a `Release` build), then when you specify the `.\bin` directory WPA will try to load both builds. That could also cause the error you're seeing.

**Comment by Alois-xx** [comment]
Hi @mslukebo,

yes that did fix the issue. 
Deleting the other folder did prevent loading the plugin twice which did lead to the KeyException.

Thanks!
