### ISSUE TITLE
WPA crashing-to-desktop as soon as it loads my plugin [SOLVED]

### ISSUE THREAD

**Issue by tpn** [microsoft/microsoft-performance-toolkit-sdk#49]
So, I got my first plugin authored, based off the [msquic](https://github.com/microsoft/msquic/tree/main/src/plugins/wpa) one (which was a great reference; you should have a wiki page linking open source examples like that).

WPA recognized the plugin when I did `wpa.exe -addsearchdir c:\foo -listplugins`, however, every time I tried to load my trace file via `wpa.exe -addsearchdir c:\foo -i c:\foo\trace.xyz`, it would just crash to the desktop with no error message or any form of feedback.

After a bit of trial and error, I ended up creating a junction in the `WPA\CustomDataSource` to my `bin\Release` directory, then loaded WPA via `wpa.exe`.  That at least didn't crash, at let me look at the Diagnostic Console, which indicated my plugin was definitely being loaded.

I then opened the `c:\foo\trace.xyz` file, and saw this:

```
Unable to process 'file:///C:/foo/trace.xyz': System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.66.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.66.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at WpaSensorPlugin.SensorEventParser.ProcessEtwSource(ISourceDataProcessor`3 dataProcessor, IProgress`1 progress, CancellationToken cancellationToken)
   at WpaSensorPlugin.SensorEventParser.ProcessSource(ISourceDataProcessor`3 dataProcessor, ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.Extensibility.SourceProcessingSession`3.ProcessSource(ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBaseWithSourceParser`3.ProcessAsyncCore(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBase.ProcessAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.CustomDataSourceExecutor.ExecuteAsync(CancellationToken cancellationToken)


Unable to process any data sources.
```

Ah!  After some more trial and error, I noticed that the commandline helper project I wrote (i.e. basically the same thing as the `QuicEtw` tool which just drives the pipeline outside of WPA) had the `Microsoft.Diagnostic.Tracing.TraceEvent.dll` file and a few others, so, I copied them manually into the plugin's `bin\Release` directory, and that worked, WPA successfully loaded my plugin and depicted my tables.

I'm not familiar enough with C#/NuGet to know if this is expected behavior or not, but I figured I'd capture it here anyway in case someone else runs into this.

Also, it'd be nice not to crash to desktop with no feedback in the first case :-)

**Comment by mslukebo** [comment]
Hi @tpn,

I'm glad you were able to get to the root of your issue. WPA is not actually crashing in this scenario - it survives failing to process a file 😄 

What's happening is that WPA will close if it's been opened with a file passed in and fails to process anything. From WPA's perspective, it's been asked to open a file. If it cannot open the file, it has nothing to do, so it closes. Perhaps we can offer a way to redirect diagnostic console to assist in debugging.

With regards to a wiki page linking to msquic: we encourage any PRs that aid in documentation 😃. If you've come across resources that you find particularly useful, it would be great to compile them and submit a PR to augment the `./documentation` folder.

**Comment by tpn** [comment]
Ah, ok, that explains the WPA behavior I'm seeing, thanks.  Re: Feedback Hub... I'd forgotten I could raise WPA-related things there, thanks for the reminder!

**Comment by mslukebo** [comment]
> Ah, ok, that explains the WPA behavior I'm seeing, thanks. Re: Feedback Hub... I'd forgotten I could raise WPA-related things there, thanks for the reminder!

After some discussion we decided to take WPA questions here (as long as they involve interaction with the SDK in some way). I edited out the Feedback Hub part of my earlier response 😄
