### ISSUE TITLE
PID re-use and process names; how's WPA handle it?

### ISSUE THREAD

**Issue by tpn** [microsoft/microsoft-performance-toolkit-sdk#52]
I've written some scaffolding in my plugin to extract `MSNT_SystemTrace/Process/(DCStart|DCStop|Start|Stop)` events and build a little lookup table.  When parsing my custom events, where I have a timestamp and PID, I can extract the relevant process start/stop event by finding a matching entry in my lookup table where the PID and start/end timeframe agree.  This allows me to easily include things like command line, and, image file name, which are very useful to include in my custom tables (versus just "process ID").

WPA has various tables with "Process" columns that are in the format `<procname> (process ID)>`, i.e. `chrome.exe (91015)`.  I took the same approach (i.e. my left-of-yellow-bar column is `processDisplayNameColumnConfig`, which generates things like `chrome.exe (91015)`), but I'm curious how WPA would handle overlapping processes that happened to have the same exe name and PID, even though this would be presumably quite rare for any given trace.

Does it do some stuff behind the scenes to disambiguate duplicate `<procname> (process ID)` column values?  i.e. appending `#2` or something for any dupes.  Or perhaps when kernel event tracing is enabled, kernel PID re-use is temporarily inhibited?  (That seems less likely.)  In my case, the column controls unique grouping, so the presence of dupes would break the aggregation accounting.

Just curious what the precedent is.  I realize this is far more of a WPA question than a plugin SDK question, but hey, that's to be expected until the WPA team set up a github issue repo too :-)

**Comment by mslukebo** [comment]
Hi @tpn,

When you say "handle __overlapping__ processes," do you mean two processes that at some point exist at the same time? Two processes that overlap in time cannot have the same PID, since PIDs can only be re-used once the handle to process the PID is assigned to is destroyed. See [here](https://devblogs.microsoft.com/oldnewthing/20110107-00/?p=11803).

Now, other possibility is "what if one instance of chrome.exe has PID 100, and then it's closed, and a new instance of chrome.exe is later started and also assigned PID 100?" Is this what you mean by "overlap" in your original post?

**Comment by tpn** [comment]
Yeah, sorry, that second example is what I mean; opened, closed, opened again and by chance has the same PID as the original one.

**Comment by mslukebo** [comment]
While I'm not sure if WPA does anything to detect this, I think it would be evident by the graph. For example, I can primarily see this happening if a trace occurs over a restart.

Once you figure out when the transition from one instance to another happens, you can use an [annotation](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/annotations#:~:text=Annotation%20is%20a%20user%2Ddefined,a%20part%20of%20the%20presets.) to annotation rows with a timestamp before the transition. If you pivot about the annotation column after the PID column, the two instances will be grouped separately.

**Comment by tpn** [comment]
It'd be nice to know how WPA officially handles things, but, in lieu of that, the annotation is a good suggestion.  Thanks!
