### ISSUE TITLE
Sample Documentation

### ISSUE THREAD

**Issue by nibanks** [microsoft/microsoft-performance-toolkit-sdk#7]
It'd be really helpful to have a pointer in your main readme to find any sample (I assume) you have.

**Comment by trgibeau** [comment]
Thanks @nibanks, we are working on uploading samples and updating documentation. Will close this when they are updated

**Comment by mslukebo** [comment]
Closing this since `develop` just received a first round of documentation. We will be working to improve this documentation over time as well.
